# Development and Test environment configurations are listed here
# for convenience but generally shouldn't be used.
#
# Replace YOUR_APP with the heroku app name and YOUR_TOKEN with the
# same token used in private_pub.yml of your rails project.

production:
  server: "https://stoop-faye.herokuapp.com/faye"
  secret_token: "caac912706e97fea4864b8bc7d26346cce11bed06b37027cf66e5db56c853740"
  signature_expiration: 3600 # one day
